[package]
name = "p2p-file-system"
version = "0.1.0"
edition = "2021"

[dependencies]
socket2 = "0.4"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"